name:live_signal_scanner.py

on:
  schedule:
    - cron: '0,30 * * * *'
  workflow_dispatch:

jobs:
  scan_market:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools wheel
          pip install -r requirements.txt

      - name: Run Scanner
        env:
          NFTY_URL: ${{ secrets.NFTY_URL }}
        run: python live_signal_scanner.py
